folksy-squid/Picky-Notes

package.json
=> more basic setup

client/index.html, client/src/components/Landing.jsx, client/src/components/Lobby.jsx, client/src/components/ParticipantList.jsx, client/src/reducers/reducer2.js, client/styles/style.css, package.json, server/config/middleware.js, server/server.js
- Substitute font awesome with Ion Icons
- Create ParticipantList component
> Currently just has dummy user data
- Create a clipboard for the sharable link in the Lobby
> Also had dummy link data
- Create npm dev script to automate webpack compiling
> npm run dev
Lobby.jsx
=> Create ParticipantList, shareable link, and npm dev script

client/src/Connection.js, client/src/components/App.jsx, client/src/components/JoinRoom.jsx, client/src/components/Main.jsx, client/src/components/Navbar.jsx, client/src/index.jsx, webpack.config.js
Fix webpack.config to not have hot reloading and modularize connection to connect the store to main and subcomponents
webpack.config and connection.js
=> Fix react router children

server/cache.js, server/cache/cache-config.js, server/cache/cache-helpers.js, server/config/passport.js, server/database/db-helpers.js, server/sockets/io-helpers.js, server/sockets/io.js, specs/Server/ServerSpec.js
- Add ready functionality
> When all users are ready, 
> transfer all notes from the cache to the database
> deletes all notes from redis
> write tests
server/sockets/io.js
npm test
=> Save all notes when all users are ready

README.md, client/src/components/sub/LectureBox.jsx, client/src/components/sub/LectureTitle.jsx, client/src/components/sub/Note.jsx, client/src/components/sub/NoteList.jsx, client/src/components/sub/ParticipantList.jsx, client/src/index.jsx
I made some changes to the notelist and note component to render views depending on the pathUrl of the page.  Also fixed a lot of bugs. Mostly fixed a lot of bugs...
=> Made changes to NoteList, Note, ParticipantList and Lecture Components

server/database/db-config.js, server/server.js, server/sockets/io-helpers.js, server/sockets/io.js, specs/Server/ServerSpec.js
- Fix and refactor Server-side spec tests and clean up console logs in code
> Hopefully fixed travis error on tests as well
io.js, io-helpers.js and serve specs
npm test should run both server and client side tests
code was ugly
=> Cleanup Specs and Sockets

package.json, server/database/db-helpers.js, server/sockets/io-helpers.js, server/sockets/io.js, specs/Client/helpers.js, specs/Server/ServerSpec.js, specs/Server/database/helperSpec.js
Notes are now multiplied for all users in the room on ready.
io.js on server side.
tests are written in specs/server/database/helpers.js
nope.
=> Multiply Notes

client/src/actions/noteActions.js, client/src/components/Compile.jsx, client/src/components/Lecture.jsx, client/src/components/Notebook.jsx, client/src/components/sub/NoteList.jsx, client/src/reducers/noteReducers.js
=> Handshakes

client/src/components/Lobby.jsx, client/src/components/sub/ParticipantList.jsx
what the title says.
Lobby.jsx.
=> componentwillunmount removes socket listener for user disconnect

client/src/actions/noteActions.js, client/src/components/JoinRoom.jsx, client/src/components/Lecture.jsx, client/src/components/Lobby.jsx, client/src/components/sub/InputBox.jsx, client/src/components/sub/LectureTitle.jsx, client/src/components/sub/Note.jsx, client/src/components/sub/NoteList.jsx, client/src/components/sub/ParticipantList.jsx, client/src/reducers/noteReducers.js, client/src/routes.jsx, client/styles/style.css, package.json, server/sockets/io.js
- render checkboxes and display checked if note.show === true
- remove continueButton
- end lecture button is only visible for the host even when the host leaves
- end lecture button will disappear when clicked
- end lecture makes the ready button visible
- auto redirect to compile page when all users are ready
- ready button can will disappear when clicked
- notes cannot be created if there is no input
lecture.jsx and compile.jsx
=> Add proper functionality for buttons and input

server/config/passport.js, server/database/db-config.js
=> production db on aws

client/src/actions/noteActions.js, client/src/components/Compile.jsx, client/src/components/Lecture.jsx, client/src/components/Review.jsx, client/src/components/sub/InputBox.jsx, client/src/components/sub/LectureTitle.jsx, client/src/components/sub/Note.jsx, client/src/components/sub/ParticipantList.jsx, client/src/reducers/noteReducers.js, webpack.config.js
- Properly rename selectNotes to toggleNotes
- Changed Save button to Review.
- Changed notes during the compile view will be sent to the server when the review button is clicked.
=> Send changed notes from compiled page to server on Review button click

client/src/components/Compile.jsx
Fix api route for updating notes
=> Fix api route for updating notes

client/index.html, client/src/components/Compile.jsx, client/src/components/Review.jsx, client/src/components/sub/Note.jsx, client/src/components/sub/NoteList.jsx, client/src/routes.jsx
Also modularize notelist and added review endpoint to routes.jsx
=> Link compile to review notes page.

server/config/passport.js
fix clientId for when node_env=test
=> fix clientId

client/src/components/Compile.jsx, client/src/components/Review.jsx, client/src/components/sub/NoteList.jsx, client/src/components/sub/ParticipantList.jsx
can access compile view directly and added sample mp3 file.
=> fixed compile view refreshing and linking and mp3

client/src/actions/chatActions.js, client/src/components/Compile.jsx, client/src/components/Lobby.jsx, client/src/components/sub/ChatBox.jsx, client/src/components/sub/Message.jsx, client/src/components/sub/ParticipantList.jsx, client/src/reducers/chatReducers.js, client/src/reducers/roomReducers.js, client/styles/style.css, package.json, server/config/hotreload.js, server/config/middleware.js, server/config/routes.js, server/sockets/io.js, webpack.config.js
- Configure hot reloading 
- Update lobby page 
- Add chatbox and message components
- Delete wildcard routes 
- Create chatactions and reducers
- Update and style ChatBox
- Update package.json
- Update webpack.config
=> Hot Reload works on 'npm run client'

client/src/actions/noteActions.js, client/src/components/Compile.jsx, client/src/components/Lecture.jsx, client/src/components/NewRoom.jsx, client/src/components/sub/EntryList.jsx, client/src/components/sub/InputBox.jsx, client/src/components/sub/LectureTitle.jsx, client/src/components/sub/Note.jsx, client/src/components/sub/NoteList.jsx, client/src/components/sub/ParticipantList.jsx, client/src/reducers/noteReducers.js, client/src/reducers/roomReducers.js, package.json, server/cache/cache-helpers.js, server/config/middleware.js, server/database/controllers/NoteController.js, server/database/controllers/RoomController.js, server/database/db-helpers.js, server/sockets/io-helpers.js, server/sockets/io.js, webpack.config.js
- Select/Deselect notes actually work the redux way
- Submitting notes in the compile page save directly to the database
- Rooms now have a start time
- Notes audioTimestamp is now text instead of date
=> Fix compile page note submission

.gitignore, client/src/actions/roomActions.js, client/src/components/Lecture.jsx, client/src/components/Lobby.jsx, client/src/reducers/roomReducers.js, package.json, server/config/audioUpload.js, server/sockets/io-helpers.js, server/sockets/io.js
records audio and saves into .wav file in audio folder
=> Record audio

server/config/routes.js, server/database/db-helpers.js
add server endpoint to grab audioUrl from pathUrl
=> add server endpoint to grab audioUrl from pathUrl

server/sockets/io.js
- Add ready check when someone disconnects from a room
- io.js
=> Add ready check when someone disconnects from a room

server/sockets/io-helpers.js
=> Hotfix for ready check on 1 user disconnect

server/config/audioUpload.js, server/config/routes.js, server/sockets/io.js
=> Audio upload Server to S3 

client/src/components/Compile.jsx, client/src/components/Navbar.jsx, client/src/components/Notebook.jsx, client/src/components/sub/Entry.jsx, client/styles/style.css, server/config/routes.js, server/server.js
- going to the compile page will disconnect the socket
- sort lectures in Notebook with the most recent on top
- create endpoint to check the status of the room
- clicking on lectures in Notebook will check the status of the room
> if inactive, redirects to review page
=> Create endpoint check room status, Disconnect sockets on compile page

client/src/components/Compile.jsx, client/src/components/Lecture.jsx, client/src/reducers/roomReducers.js, server/database/controllers/RoomController.js, server/database/db-helpers.js, server/sockets/io-helpers.js, server/sockets/io.js
Handing back the task to Marco to rejoin lecture and reconnect socket..
=> This one's for Marco

client/src/actions/noteActions.js, client/src/components/Review.jsx, client/src/components/sub/Audio.jsx, client/src/reducers/noteReducers.js, client/src/reducers/roomReducers.js, client/src/routes.jsx
you can't see the audio before it loads. Have options to handle loading.
=> handled loading for audio component

client/src/components/Compile.jsx, client/src/components/Lecture.jsx, client/src/components/Lobby.jsx, client/src/components/Notebook.jsx, client/src/components/sub/Entry.jsx, client/src/components/sub/Note.jsx, client/src/components/sub/ParticipantList.jsx, client/src/components/sub/ShareLink.jsx, client/src/reducers/noteReducers.js, client/src/reducers/roomReducers.js, server/cache/cache-helpers.js, server/database/db-helpers.js, server/sockets/io-helpers.js, server/sockets/io.js, specs/Server/database/helperSpec.js
- Be able to view the compile page
> Only disconnect socket if you have a socket connection.
- Be able to reconnect to an active lecture
> Host transfer works for users who join the room with a lecture link
- Does not display rooms that have not started in Notebook view
- Rejoining an active room will display previously entered notes from redis
- Be able to join active lobbies with the share url
> Host transfer works for users who join the room with a lobby link
=> Be able to reconnect to active lectures

client/src/actions/noteActions.js, client/src/actions/waveformActions.js, client/src/components/Compile.jsx, client/src/components/sub/Audio.jsx, client/src/components/sub/InputBox.jsx, client/src/components/sub/LectureBox.jsx, client/src/components/sub/Note.jsx, client/src/components/sub/NoteList.jsx, client/src/reducers/noteReducers.js, client/src/reducers/waveformReducers.js, client/styles/style.css
- Added a dynamic setTimeout to check for upcoming audio timestamp in note list
- Notereducer returns an object state instead of an array of notes
=> Audio wave now knows when to trigger action on note

client/src/components/Lecture.jsx, client/src/components/Lobby.jsx, client/src/reducers/noteReducers.js
- remove unnecessary code
- fix replace cb issue
=> [Dev] remove unnecessary code, fix replace cb issue

client/src/components/Lecture.jsx, client/src/components/sub/Note.jsx, client/src/components/sub/NoteList.jsx, client/src/reducers/noteReducers.js, client/styles/style.css
- Add "highlight" property to note on timer in noteReducer
- Remove "highlight" from previous note if another note is to be "highlight"-ed
- Add border-left to note-list and pointer to a div below note if it has a "highlight" property.
- Start at noteReducer
=> Add pointer to compile view 

appspec.yml, bin/app-start.sh, bin/install-pkgs.sh, example_keys.js
Add appspec.yml and bash scripts in bin folder for deployment.
=> Add necessary files for deployment

example_keys.js
=> fix example keys

client/src/actions/noteActions.js, client/src/components/Compile.jsx, client/src/components/Review.jsx, client/src/components/sub/Audio.jsx, client/src/components/sub/LectureBox.jsx, client/src/components/sub/Note.jsx, client/src/components/sub/NoteList.jsx, client/src/reducers/noteReducers.js, client/src/routes.jsx
Audio now can be toggle played and clicked around.
Audio jsx and reducer.
=> Audioselect

client/src/components/Notebook.jsx, client/src/components/sub/Dropdown.jsx, client/src/components/sub/SearchBar.jsx
Add dropdown filter component for notebooks to filter by class and fix kunal's bug
=> Searchfilter

client/src/components/sub/NoteList.jsx
=> correct my fuckup for not including kunals fuck up

client/index.html, client/src/actions/noteActions.js, client/src/components/Compile.jsx, client/src/components/sub/Audio.jsx, client/src/components/sub/InputBox.jsx, client/src/components/sub/Note.jsx, client/src/components/sub/NoteList.jsx, client/src/components/sub/ParticipantList.jsx, client/src/reducers/noteReducers.js, client/src/reducers/roomReducers.js, client/styles/style.css, server/config/routes.js, server/database/db-helpers.js
- Disconnect existing sockets before creating or joining rooms.
> Creating or joining a room will disconnect your current socket (if exists).
- Indicate who is the host.
> Hosts will have `(Host)` next to their name.
- No longer need forceUpdate for rendering checkboxes
> Reducer returns a new object with state properties instead of state.
- Add note deletion functionality on compile page.
> new DELETE endpoint was created to delete notes.
- Adding notes on the compile page will be timestamped with the current audio position.
> Warning: this messes up the cursor tied with the audio.
everywhere
=> bug fixes, host indicator, delete notes, timestamp new notes on compile

client/src/components/Notebook.jsx, client/src/components/sub/Dropdown.jsx, client/src/components/sub/SearchBar.jsx, example_keys.js
read the title
go to notebook view and search by topic, class, or lecturer
=> add filter by topic and lecturer to notebooks

client/src/components/Compile.jsx, client/src/components/JoinRoom.jsx, client/src/components/Lecture.jsx, client/src/components/sub/ParticipantList.jsx, client/src/components/sub/ShareLink.jsx, client/src/reducers/roomReducers.js, server/sockets/io.js
- Joining a lecture that has already started with the code will take you to lecture view instead of the lobby
- Share Link will now reflect the domain on where it is being hosted on
-  Update all button views for sockets with the same id
=> Entering code will take you to active lecture, better share link, updated buttons

client/src/reducers/noteReducers.js, server/database/db-helpers.js
=> Save thought to the database

client/index.html, client/src/actions/noteActions.js, client/src/components/Compile.jsx, client/src/components/Lecture.jsx, client/src/components/Notebook.jsx, client/src/components/sub/Audio.jsx, client/src/components/sub/InputBox.jsx, client/src/components/sub/LectureBox.jsx, client/src/components/sub/Note.jsx, client/src/reducers/noteReducers.js, client/styles/style.css
- Display input, audio controls, and waveform at the bottom at a fixed position.
- Animate to slide up after rendering the page
- Typing into the input displays the time that it will be stamped with.
- Render a play button (renders a pause button if it is playing)
- Use https for ion icons cdn
- Searching for notes is case-insensitive now
- Toggle waveform.playing to false when audio is done playing
- Edit timestamps in compile view
- Audio.jsx and InputBox.jsx
=> Display input and audio at fixed position bottom, input displays timestamp

client/src/reducers/waveformReducers.js
=> Fix togglePlay

client/src/components/Compile.jsx, client/src/components/Lecture.jsx, client/src/components/Lobby.jsx, client/src/components/sub/Note.jsx, client/styles/style.css
=> Button medium and modularize the note and classes.

client/src/actions/noteActions.js, client/src/components/sub/InputBox.jsx, client/src/components/sub/Note.jsx, client/src/components/sub/NoteList.jsx, client/src/reducers/noteReducers.js, client/styles/style.css
Adds an indicator of where you will be adding a note.
=> Note indicator

client/src/actions/noteActions.js, client/src/components/Review.jsx, client/src/components/sub/Note.jsx, client/src/components/sub/NoteList.jsx, client/src/components/sub/ThoughtList.jsx, client/src/reducers/noteReducers.js, client/styles/style.css
=> Add thoughtlist to the review page

client/src/components/sub/Entry.jsx, client/src/components/sub/EntryList.jsx, client/src/components/sub/Note.jsx, client/src/components/sub/NoteList.jsx, client/styles/style.css, package.json, yarn.lock
basic styling for notebook view
=> Notebookview

client/src/components/Review.jsx, client/src/components/sub/Audio.jsx, client/src/components/sub/InputBox.jsx, client/styles/style.css
- waveform is at the fixed at the bottom on the review page
- Displays current time and total time of the audio
=> Waveform at bottom at review, displays current and total length of the audio

client/index.html, client/src/components/Lecture.jsx, client/src/components/Lobby.jsx, client/src/components/Navbar.jsx, client/src/components/Notebook.jsx, client/src/components/sub/Entry.jsx, client/src/components/sub/SearchBar.jsx, client/styles/style.css, client/styles/w3schools.css, server/config/routes.js
Add position:fixed to participant list and lecture buttons, cleaned up lecture view, style the notebook page, use a consistent font across the views, change navbar style
everywhere
=> A lot of styling changes

client/src/components/Compile.jsx, client/src/components/Lecture.jsx, client/src/components/Review.jsx, client/src/components/sub/InputBox.jsx, client/src/components/sub/Note.jsx, client/src/components/sub/ShareLink.jsx, client/styles/style.css, yarn.lock
- Lecture and Compile inputboxes are aligned with the noteList and has the same width
- clicking on the link will select the entire link and automatically copy to clipboard
> Realigns on window resize
=> Inputbox is aligned and has the same width as notes

client/src/components/Review.jsx, client/src/components/sub/ThoughtList.jsx, client/styles/style.css, package.json
=> thoughts expandable panel

.travis.yml, database-setup.bash, example_keys.js, server/database/db-config.js, yarn.lock
=> hooray for travis

client/index.html, client/src/components/App.jsx, client/src/components/Compile.jsx, client/src/components/Landing.jsx, client/src/components/Lecture.jsx, client/src/components/Lobby.jsx, client/src/components/Navbar.jsx, client/src/components/NewRoom.jsx, client/src/components/Notebook.jsx, client/src/components/Review.jsx, client/src/components/sub/Audio.jsx, client/src/components/sub/ChatBox.jsx, client/src/components/sub/Entry.jsx, client/src/components/sub/LectureBox.jsx, client/src/components/sub/LectureTitle.jsx, client/src/components/sub/NoteList.jsx, client/src/landing.js, client/src/scrollStuff.js, client/styles/style.css, package.json, server/config/routes.js
Fix landing page stuff and added shadow to navbar scroll and fix lecture
=> Fix landing page

audio/index.js, client/src/components/Lobby.jsx, client/src/components/sub/Audio.jsx, client/src/reducers/roomReducers.js, package.json, server/config/audioUpload.js, server/sockets/io.js, yarn.lock
- Improve audio quality
- Creates audio stream from microphone using mediaDevices.getUserMedia
- Records using MediaRecorder API
- Sends blobs/data to server through sockets in large chunks
- Blobs automatically gets converted to buffers
- Buffers are written to disk as an audio file
- Audio file is converted to mp3
- Uploads mp3 file to AWS
roomReducers.js and io.js
=> Improve audio quality

.gitignore, client/src/components/sub/Note.jsx, client/src/reducers/roomReducers.js, server/database/db-helpers.js, server/sockets/io.js
- FIx editing notes.
- Recording symbol on chrome disappears now after recording ends.
=> Fix edit notes and recording symbol disappears after recording ends

client/src/components/sub/Audio.jsx, yarn.lock
=> Change waveform message

README.md, example_keys.js, server/config/middleware.js, webpack.config.js
=> optimizations for server

client/index.html, client/src/components/sub/Audio.jsx, server/cache/cache-helpers.js
=> more optimizations, commenting

client/src/components/Landing.jsx, client/src/components/sub/Audio.jsx, client/styles/style.css
=> completed landing page styling

client/src/components/Landing.jsx, client/styles/style.css
=> Landing page looks awesome now

client/src/components/sub/Audio.jsx
Set audio url into roomInfo on mount
=> Get audio url on mount

.gitignore, client/src/components/Landing.jsx, server/server.js
=> Add thesis.pem to gitignore, Update Landing Page coverr video
